version: '3.8'

services:

  kong-database:
    image: postgres:13
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kongpass
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    networks:
      main:
        aliases:
          - postgresql

  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    networks:
      main:
        aliases:
          - kong-migration
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kongpass
    links:
      - kong-database
    depends_on:
      - kong-database

  kong:
    image: kong:latest
    restart: always
    networks:
      main:
        aliases:
          - kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
    depends_on:
      - kong-migration
      - kong-database
    ports:
      - "8001:8001"
      - "8000:8000"

networks:
    main:
        external: true